### ISSUE TITLE
Hammond Manufacturing meta information require case-insensitive

### ISSUE THREAD

**Issue by sethhillbrand** [Digi-Key/digikey-partner-kicad-library#2]
The html files (meta/info.html) for the Hammond manufacturing link to "brd.png" for the board previews.  The files are named brd.PNG (capital letters PNG).  On case-sensitive file systems, this does not resolve correctly.

The files should be renamed to lower case names to function properly.

**Comment by Reid-L** [comment]
Seth,
Thank you for the feedback. I will get to fixing those as soon as possible and will note that for the future.

Reid L.

**Comment by Reid-L** [comment]
@sethhillbrand 

Thank you again for your feedback, very helpful. This issue should be corrected on pull request #3 

Reid L.

**Comment by sethhillbrand** [comment]
Issue has been resolved
